# Generated by Django 5.0.6 on 2024-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سرویس')),
                ('image', models.ImageField(upload_to='services', verbose_name='تصویر سرویس')),
                ('icon', models.ImageField(upload_to='services', verbose_name='آیکون سرویس')),
                ('description', models.TextField(verbose_name='توضیحات سرویس')),
                ('short_description', models.CharField(max_length=200, verbose_name='توضیحات کوتاه سرویس')),
                ('possibilities', models.CharField(max_length=300, verbose_name='امکانات سرویس')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
    ]
