# Generated by Django 5.0.6 on 2024-07-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinksCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی لینک های پایین صصفحه')),
            ],
            options={
                'verbose_name': 'عنوان دسته بندی لینک پایین صفحه',
                'verbose_name_plural': 'عنوان دسته بندی لینک های پایین صفحه',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='home.footerlinkscategory', verbose_name='دسته بندی لینک')),
            ],
            options={
                'verbose_name': 'لینک پایین صفحه',
                'verbose_name_plural': 'لینک های پایین صفحه',
            },
        ),
    ]
