# Generated by Django 5.0.6 on 2024-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='چک شده/نشده'),
        ),
    ]
