# Generated by Django 5.0.6 on 2024-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('image', models.ImageField(upload_to='team_members', verbose_name='تصویر')),
                ('skill', models.CharField(max_length=100, verbose_name='مهارت')),
            ],
            options={
                'verbose_name': 'اعضای تیم',
                'verbose_name_plural': 'اعضا های تیم',
            },
        ),
    ]
