# Generated by Django 5.0.6 on 2024-07-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_teammembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_site',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='لوگوی سایت'),
        ),
    ]
